swagger: '2.0'
info:
  description: DocumentsAPI Documentation
  version: '1.0'
  title: DocumentsAPI Documentation
  termsOfService: 'urn:tos'
  contact: {}
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'
host: 'localhost:8080'
basePath: /
tags:
  - name: controller
    description: Controller
paths:
  /document:
    get:
      tags:
        - controller
      summary: getByEntityType
      operationId: getByEntityTypeUsingGET
      produces:
        - '*/*'
      parameters:
        - name: entityType
          in: query
          description: entityType
          required: false
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/EntityData'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
    post:
      tags:
        - controller
      summary: addDocument
      operationId: addDocumentUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: addEntityDoc
          description: addEntityDoc
          required: true
          schema:
            $ref: '#/definitions/AddEntityDoc'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/DocumentCreateResponse'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  '/document/{entityId}':
    get:
      tags:
        - controller
      summary: getDocuments
      operationId: getDocumentsUsingGET
      produces:
        - '*/*'
      parameters:
        - name: entityId
          in: path
          description: entityId
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/GetEntityDoc'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
    put:
      tags:
        - controller
      summary: updateDocuments
      operationId: updateDocumentsUsingPUT
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: entityId
          in: path
          description: entityId
          required: true
          type: string
        - in: body
          name: updateEntityDoc
          description: updateEntityDoc
          required: true
          schema:
            $ref: '#/definitions/UpdateEntityDoc'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/DocumentUpdateResponse'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
definitions:
  AddEntityDoc:
    type: object
    properties:
      documents:
        type: array
        items:
          $ref: '#/definitions/DocData'
      entityId:
        type: string
    title: AddEntityDoc
  DocData:
    type: object
    properties:
      data:
        type: string
        format: byte
      documentType:
        type: string
      verified:
        type: boolean
    title: DocData
  DocumentCreateResponse:
    type: object
    properties:
      status:
        type: string
    title: DocumentCreateResponse
  DocumentData:
    type: object
    properties:
      documentId:
        type: string
      documentLink:
        type: string
      documentType:
        type: string
      id:
        type: string
      verified:
        type: boolean
    title: DocumentData
  DocumentUpdateResponse:
    type: object
    properties:
      status:
        type: string
    title: DocumentUpdateResponse
  EntityData:
    type: object
    properties:
      date:
        type: string
      documentId:
        type: string
      entityId:
        type: string
      verfied:
        type: boolean
    title: EntityData
  GetEntityDoc:
    type: object
    properties:
      documents:
        type: array
        items:
          $ref: '#/definitions/DocumentData'
      entityId:
        type: string
    title: GetEntityDoc
  UpdateEntityDoc:
    type: object
    properties:
      documents:
        type: array
        items:
          $ref: '#/definitions/DocData'
    title: UpdateEntityDoc
