cloud:
  aws:
    credentials:
      access-key: AKIAWIXA4BGH7CB7ITOA
      secret-key: 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
      
    region:
      static: ap-south-1
      auto: false
      
    stack:
      auto: false
      

     
      