cloud:
  aws:
    credentials:
      access-key: Enter access key
      secret-key: Enter secret key
      
    region:
      static: ap-south-1
      auto: false
      
    stack:
      auto: false
      

     
      